-- 숫자 데이터 형식
--  INT: 4byte 정수 , +- 21억범위
-- a : 1byte , 가 3~4 byte
-- BIGINT : 8byte 정수,범위 +-900경 범위
-- float: 4byte 실수, 소수점 아래 7자리까지 표현
-- DOUBLE: 8byte 실수, 소수점 아래 15자리까지 표현
-- DECIMAL : 5~15byte, 소수점 아래 자리를 지정가능
-- 예) DECIMAL(6,2)
-- 9999.99
--  문자 데이터 형식
-- CHAR(n) : 1~255byte , n만큼 고정길이를 가지는 문자형
-- VARCHAR(n) : 1~65535byte, n만큼 가변길이를 가지는 문자형
-- LONGTEXT : 최대 4Gb, text 데이터 값을 저장
-- LONGBLOB : 최대4Gb, BLOB 데이터 값을 저장
-- ENUM : 정해진 값만 입력 가능하도록 하는 데이터 형식
-- 날짜 및 시간 데이터 형식
-- DATE : 3byte, 'YYYY-MM-DD' 1001-01-01~9999-12-31 날짜까지 저장
-- DATETIME : 8byte, 'YYYY-MM-DD' hh:mi:ss'
