SHOW FUNCTION STATUS;

SHOW CREATE FUNCTION my_sum;

DELIMITER $$
CREATE FUNCTION my_sum(num1 INT, num2 INT)
	RETURNS INT
BEGIN
	RETURN num1+num2;
END $$
DELIMITER ;

CREATE FUNCTION my_sum(num1 INT, num2 INT)
	RETURNS INT
BEGIN
	RETURN num1+num2;
END;

DELIMITER $$
CREATE FUNCTION my_sum1(num1 INT, num2 INT)
	RETURNS INT
BEGIN
	RETURN num1+num2;
END $$
DELIMITER ;