CREATE DATABASE mini_board2;
USE mini_board2;

CREATE TABLE board2 (
	id INT PRIMARY KEY AUTO_INCREMENT
	,title VARCHAR(100) NOT NULL
	,content VARCHAR(1000) NOT NULL
	,create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,update_at DATETIME DEFAULT NULL
	,delete_at DATETIME DEFAULT NULL
	,delete_flag CHAR(1) NOT NULL DEFAULT '0'
);
